import 'package:flutter/material.dart';

import '../lib/flutter_tree.dart';

var serverData = [
  {
    "attributes": [],
    "canSelected": true,
    "checked": true,
    "checkedStatus": 1,
    "children": [
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [],
            "hasChild": true,
            "iconCls": 1,
            "id": 111,
            "pid": 11,
            "state": "closed",
            "text": "零售业务线孙1",
          },
        ],
        "hasChild": true,
        "iconCls": 1,
        "id": 11,
        "pid": 1,
        "state": "closed",
        "text": "零售业务线子1",
      },
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [],
        "hasChild": true,
        "iconCls": 1,
        "id": 12,
        "pid": 1,
        "state": "closed",
        "text": "零售业务线子2",
      },
    ],
    "hasChild": true,
    "iconCls": 1,
    "id": 1,
    "pid": 0,
    "state": "closed",
    "text": "零售业务线1",
  },
  {
    "attributes": [],
    "canSelected": true,
    "checked": true,
    "checkedStatus": 1,
    "children": [
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [
              {
                "attributes": [],
                "canSelected": true,
                "checked": true,
                "checkedStatus": 1,
                "children": [],
                "hasChild": true,
                "iconCls": 1,
                "id": 111,
                "pid": 11,
                "state": "closed",
                "text": "零售业务线孙1",
              },
            ],
            "hasChild": true,
            "iconCls": 1,
            "id": 11,
            "pid": 1,
            "state": "closed",
            "text": "零售业务线子1",
          },
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [],
            "hasChild": true,
            "iconCls": 1,
            "id": 12,
            "pid": 1,
            "state": "closed",
            "text": "零售业务线子2",
          },
        ],
        "hasChild": true,
        "iconCls": 1,
        "id": 1,
        "pid": 0,
        "state": "closed",
        "text": "零售业务线1",
      },
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [
              {
                "attributes": [],
                "canSelected": true,
                "checked": true,
                "checkedStatus": 1,
                "children": [],
                "hasChild": true,
                "iconCls": 1,
                "id": 111,
                "pid": 11,
                "state": "closed",
                "text": "零售业务线孙1",
              },
            ],
            "hasChild": true,
            "iconCls": 1,
            "id": 11,
            "pid": 1,
            "state": "closed",
            "text": "零售业务线子1",
          },
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [],
            "hasChild": true,
            "iconCls": 1,
            "id": 12,
            "pid": 1,
            "state": "closed",
            "text": "零售业务线子2",
          },
        ],
        "hasChild": true,
        "iconCls": 1,
        "id": 1,
        "pid": 0,
        "state": "closed",
        "text": "零售业务线1",
      },
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [
              {
                "attributes": [],
                "canSelected": true,
                "checked": true,
                "checkedStatus": 1,
                "children": [],
                "hasChild": true,
                "iconCls": 1,
                "id": 111,
                "pid": 11,
                "state": "closed",
                "text": "零售业务线孙1",
              },
            ],
            "hasChild": true,
            "iconCls": 1,
            "id": 11,
            "pid": 1,
            "state": "closed",
            "text": "零售业务线子1",
          },
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [],
            "hasChild": true,
            "iconCls": 1,
            "id": 12,
            "pid": 1,
            "state": "closed",
            "text": "零售业务线子2",
          },
        ],
        "hasChild": true,
        "iconCls": 1,
        "id": 1,
        "pid": 0,
        "state": "closed",
        "text": "零售业务线1",
      },
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [
              {
                "attributes": [],
                "canSelected": true,
                "checked": true,
                "checkedStatus": 1,
                "children": [],
                "hasChild": true,
                "iconCls": 1,
                "id": 111,
                "pid": 11,
                "state": "closed",
                "text": "零售业务线孙1",
              },
            ],
            "hasChild": true,
            "iconCls": 1,
            "id": 11,
            "pid": 1,
            "state": "closed",
            "text": "零售业务线子1",
          },
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [],
            "hasChild": true,
            "iconCls": 1,
            "id": 12,
            "pid": 1,
            "state": "closed",
            "text": "零售业务线子2",
          },
        ],
        "hasChild": true,
        "iconCls": 1,
        "id": 1,
        "pid": 0,
        "state": "closed",
        "text": "零售业务线1",
      },
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [
              {
                "attributes": [],
                "canSelected": true,
                "checked": true,
                "checkedStatus": 1,
                "children": [],
                "hasChild": true,
                "iconCls": 1,
                "id": 111,
                "pid": 11,
                "state": "closed",
                "text": "零售业务线孙1",
              },
            ],
            "hasChild": true,
            "iconCls": 1,
            "id": 11,
            "pid": 1,
            "state": "closed",
            "text": "零售业务线子1",
          },
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [],
            "hasChild": true,
            "iconCls": 1,
            "id": 12,
            "pid": 1,
            "state": "closed",
            "text": "零售业务线子2",
          },
        ],
        "hasChild": true,
        "iconCls": 1,
        "id": 1,
        "pid": 0,
        "state": "closed",
        "text": "零售业务线1",
      },
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [
              {
                "attributes": [],
                "canSelected": true,
                "checked": true,
                "checkedStatus": 1,
                "children": [],
                "hasChild": true,
                "iconCls": 1,
                "id": 111,
                "pid": 11,
                "state": "closed",
                "text": "零售业务线孙1",
              },
            ],
            "hasChild": true,
            "iconCls": 1,
            "id": 11,
            "pid": 1,
            "state": "closed",
            "text": "零售业务线子1",
          },
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [],
            "hasChild": true,
            "iconCls": 1,
            "id": 12,
            "pid": 1,
            "state": "closed",
            "text": "零售业务线子2",
          },
        ],
        "hasChild": true,
        "iconCls": 1,
        "id": 1,
        "pid": 0,
        "state": "closed",
        "text": "零售业务线1",
      },
    ],
    "hasChild": true,
    "iconCls": 2,
    "id": 2,
    "pid": 0,
    "state": "closed",
    "text": "零售业务线2",
  },
  {
    "attributes": [],
    "canSelected": true,
    "checked": true,
    "checkedStatus": 1,
    "children": [
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [],
        "hasChild": true,
        "iconCls": 2,
        "id": 3,
        "pid": 0,
        "state": "closed",
        "text": "零售业务线3",
      },
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [],
        "hasChild": true,
        "iconCls": 2,
        "id": 3,
        "pid": 0,
        "state": "closed",
        "text": "零售业务线3",
      },
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [],
        "hasChild": true,
        "iconCls": 2,
        "id": 3,
        "pid": 0,
        "state": "closed",
        "text": "零售业务线3",
      },
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [],
        "hasChild": true,
        "iconCls": 2,
        "id": 3,
        "pid": 0,
        "state": "closed",
        "text": "零售业务线3",
      },
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [],
        "hasChild": true,
        "iconCls": 2,
        "id": 3,
        "pid": 0,
        "state": "closed",
        "text": "零售业务线3",
      },
      {
        "attributes": [],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [],
        "hasChild": true,
        "iconCls": 2,
        "id": 3,
        "pid": 0,
        "state": "closed",
        "text": "零售业务线3",
      },
      {
        "attributes": [
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [],
            "hasChild": true,
            "iconCls": 2,
            "id": 3,
            "pid": 0,
            "state": "closed",
            "text": "零售业务线3",
          },
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [],
            "hasChild": true,
            "iconCls": 2,
            "id": 3,
            "pid": 0,
            "state": "closed",
            "text": "零售业务线3",
          },
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [],
            "hasChild": true,
            "iconCls": 2,
            "id": 3,
            "pid": 0,
            "state": "closed",
            "text": "零售业务线3",
          },
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [],
            "hasChild": true,
            "iconCls": 2,
            "id": 3,
            "pid": 0,
            "state": "closed",
            "text": "零售业务线3",
          },
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [],
            "hasChild": true,
            "iconCls": 2,
            "id": 3,
            "pid": 0,
            "state": "closed",
            "text": "零售业务线3",
          },
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [],
            "hasChild": true,
            "iconCls": 2,
            "id": 3,
            "pid": 0,
            "state": "closed",
            "text": "零售业务线3",
          },
        ],
        "canSelected": true,
        "checked": true,
        "checkedStatus": 1,
        "children": [
          {
            "attributes": [],
            "canSelected": true,
            "checked": true,
            "checkedStatus": 1,
            "children": [
              {
                "attributes": [],
                "canSelected": true,
                "checked": true,
                "checkedStatus": 1,
                "children": [
                  {
                    "attributes": [],
                    "canSelected": true,
                    "checked": true,
                    "checkedStatus": 1,
                    "children": [],
                    "hasChild": true,
                    "iconCls": 1,
                    "id": 111,
                    "pid": 11,
                    "state": "closed",
                    "text": "零售业务线孙1",
                  },
                ],
                "hasChild": true,
                "iconCls": 1,
                "id": 11,
                "pid": 1,
                "state": "closed",
                "text": "零售业务线子1",
              },
              {
                "attributes": [],
                "canSelected": true,
                "checked": true,
                "checkedStatus": 1,
                "children": [
                  {
                    "attributes": [],
                    "canSelected": true,
                    "checked": true,
                    "checkedStatus": 1,
                    "children": [
                      {
                        "attributes": [],
                        "canSelected": true,
                        "checked": true,
                        "checkedStatus": 1,
                        "children": [
                          {
                            "attributes": [],
                            "canSelected": true,
                            "checked": true,
                            "checkedStatus": 1,
                            "children": [],
                            "hasChild": true,
                            "iconCls": 1,
                            "id": 111,
                            "pid": 11,
                            "state": "closed",
                            "text": "零售业务线孙1",
                          },
                        ],
                        "hasChild": true,
                        "iconCls": 1,
                        "id": 11,
                        "pid": 1,
                        "state": "closed",
                        "text": "零售业务线子1",
                      },
                      {
                        "attributes": [],
                        "canSelected": true,
                        "checked": true,
                        "checkedStatus": 1,
                        "children": [
                          {
                            "attributes": [],
                            "canSelected": true,
                            "checked": true,
                            "checkedStatus": 1,
                            "children": [
                              {
                                "attributes": [],
                                "canSelected": true,
                                "checked": true,
                                "checkedStatus": 1,
                                "children": [
                                  {
                                    "attributes": [],
                                    "canSelected": true,
                                    "checked": true,
                                    "checkedStatus": 1,
                                    "children": [],
                                    "hasChild": true,
                                    "iconCls": 1,
                                    "id": 111,
                                    "pid": 11,
                                    "state": "closed",
                                    "text": "零售业务线孙1",
                                  },
                                ],
                                "hasChild": true,
                                "iconCls": 1,
                                "id": 11,
                                "pid": 1,
                                "state": "closed",
                                "text": "零售业务线子1",
                              },
                              {
                                "attributes": [],
                                "canSelected": true,
                                "checked": true,
                                "checkedStatus": 1,
                                "children": [],
                                "hasChild": true,
                                "iconCls": 1,
                                "id": 12,
                                "pid": 1,
                                "state": "closed",
                                "text": "零售业务线子2",
                              },
                            ],
                            "hasChild": true,
                            "iconCls": 1,
                            "id": 1,
                            "pid": 0,
                            "state": "closed",
                            "text": "零售业务线1",
                          },
                        ],
                        "hasChild": true,
                        "iconCls": 1,
                        "id": 12,
                        "pid": 1,
                        "state": "closed",
                        "text": "零售业务线子2",
                      },
                    ],
                    "hasChild": true,
                    "iconCls": 1,
                    "id": 1,
                    "pid": 0,
                    "state": "closed",
                    "text": "零售业务线1",
                  },
                ],
                "hasChild": true,
                "iconCls": 1,
                "id": 12,
                "pid": 1,
                "state": "closed",
                "text": "零售业务线子2",
              },
            ],
            "hasChild": true,
            "iconCls": 1,
            "id": 1,
            "pid": 0,
            "state": "closed",
            "text": "零售业务线1",
          },
        ],
        "hasChild": true,
        "iconCls": 2,
        "id": 3,
        "pid": 0,
        "state": "closed",
        "text": "零售业务线3",
      },
    ],
    "hasChild": true,
    "iconCls": 2,
    "id": 3,
    "pid": 0,
    "state": "closed",
    "text": "零售业务线3",
  },
];

class MyServerData {
  MyServerData({
    required this.attributes,
    required this.canSelected,
    required this.checked,
    required this.checkedStatus,
    required this.children,
    required this.hasChild,
    required this.iconCls,
    required this.id,
    required this.pid,
    required this.state,
    required this.text,
  });

  List<dynamic> attributes;
  bool canSelected;
  bool checked;
  int checkedStatus;
  bool hasChild;
  int iconCls;
  int id;
  int pid;
  String state;
  String text;
  List<MyServerData> children;

  factory MyServerData.fromJson(Map<String, dynamic> json) => MyServerData(
        attributes: List<dynamic>.from(json["attributes"].map((x) => x)),
        canSelected: json["canSelected"],
        checked: json["checked"],
        checkedStatus: json["checkedStatus"],
        children: List<MyServerData>.from(
          json["children"].map((x) => MyServerData.fromJson(x)),
        ),
        hasChild: json["hasChild"],
        iconCls: json["iconCls"],
        id: json["id"],
        pid: json["pid"],
        state: json["state"],
        text: json["text"],
      );
}

TreeNodeData mapServerDataToTreeNodeData(MyServerData data) {
  return TreeNodeData(
    offset: 20.0,
    onTap: (d) {
      print(d);
    },
    title: data.text,
    level: 0,
    expaned: data.checked,
    icon: Icon(
      Icons.expand_more,
      size: 24.0,
    ),
    children:
        List.from(data.children.map((x) => mapServerDataToTreeNodeData(x))),
    extra: data,
    trailing: Container(),
  );
}

List<TreeNodeData> treeData = List.generate(
  serverData.length,
  (index) => mapServerDataToTreeNodeData(
    MyServerData.fromJson(serverData[index]),
  ),
);
